---
code_config_file: /home/{{ ansible_user_id }}/.config/code-server/config.yaml
ansible_dest: /home/hyoga/code/boilerplates/ansible

keyrings_dir: /etc/apt/keyrings

deb_file: code-server

dependecies:
  - gpg
  - git
  - python3
  - python3-pip
  - apt-transport-https
  - curl
  - openssh-server
  - gnupg
  - jq
  - lsb-release
  - ca-certificates
  - yamllint
  - xclip
