- Selfhost:
    - FreshRSS:
        href: http://172.16.16.10:8087
        description: RSS Feeds
    - Home Assistant:
        href: http://172.16.16.11:8123
        description: Home Assistant
    - Code-Server:
        href: https://172.16.16.12
        description: Personal coder
    - Kavita:
        href: https://172.16.16.10:8083
        description: Library
    - Bazarr:
        href: http://172.16.10.20:6767
        description: Subtitles manager
- Media:
    - Sonarr:
        href: http://172.16.10.20:8989
        description: Series Management
    - Radarr:
        href: http://172.16.10.20:7878
        description: Movie Management
    - Overseerr:
        href: http://172.16.10.20:5055
        description: Request Tool
    - Plex:
        href: http://172.16.10.20:32400/web
        description: Entertainment
    - Prowlarr:
        href: http://172.16.10.20:9696
        description: Indexer Manager
    - Tautulli:
        href: http://172.16.10.20:8181
        description: Stats for Plex
- Management:
    - OPNsense:
        href: https://172.16.16.1
        description: FreeBSD Router
        target: _blank
    - Unifi Controller:
        href: https://172.16.16.10:8443
        description: AP Management
        target: _blank
    - TrueNAS:
        href: http://172.16.16.5
        description: NAS Controller
    - AdGuard Home:
        href: http://172.16.16.1:8080/
        description: DNS Controller
    - Cloudflare:
        href: https://dash.cloudflare.com/login
        description: DDNS Manager
    - Portainer-CE:
        href: https://172.16.16.16:9443
        description: Containerized Management
- Tools:
    - Vaultwarden:
        href: https://vault.chkpwd.com
        description: Password Manager
    - Bookstack:
        href: http://172.16.16.10:6875
        description: Library
    - Filebrowser:
        href: http://172.16.16.10:5555
        description: Stashing tool
- Downloaders:
    - SABnzbd:
        href: http://172.16.10.20:8180
        description: NZB Grubber
    - qBittorrent:
        href: http://172.16.10.20:8280
        description: Torrent Grubber
- Virtualization:
    - vSphere:
        href: http://172.16.16.6/ui
        description: vSphere Management
        target: _blank
    - Proxmox:
        href: https://172.16.16.3:8006
        description: PVE Management
        target: _blank
- misc:
    - OctoPrint:
        href: https://print.chkpwd.com
        description: 3D Printer
- Apps:
    - Sunshine:
        href: https://localhost:47990/
        description: Game streaming tool
