apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
  namespace: apps
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/home/hyoga/data/portainer"
