---
scenario:
  test_sequence:
    - create
    - converge
    #- idempotence # TODO: Find a better way to ensure idempotence
    - verify
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian10
    image: geerlingguy/docker-debian10-ansible:latest
    command: ""
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      - /var/run/dbus
    cgroupns_mode: host
    privileged: true
    pre_build_image: false
  - name: debian11
    image: geerlingguy/docker-debian11-ansible:latest
    command: ""
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      - /var/run/dbus
    cgroupns_mode: host
    privileged: true
    pre_build_image: false
  # - name: fedora37
  #   image: geerlingguy/docker-fedora37-ansible:latest
  #   command: ""
  #   volumes: 
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #     - /var/lib/containerd
  #     - /var/run/dbus
  #   cgroupns_mode: host
  #   privileged: true
  #   pre_build_image: false
  # - name: centos8
  #   image: quay.io/centos/centos:stream8
  #   command: ""
  #   volumes: 
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #     - /var/lib/containerd
  #     - /var/run/dbus
  #   cgroupns_mode: host
  #   privileged: true
  #   pre_build_image: false
  # - name: rockylinux9
  #   image: geerlingguy/docker-rockylinux9-ansible:latest
  #   command: ""
  #   volumes: 
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #     - /var/lib/containerd
  #     - /var/run/dbus
  #   cgroupns_mode: host
  #   privileged: true
  #   pre_build_image: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      debian11:
        ansible_user: ansible
  env:
    #ANSIBLE_VAULT_PASSWORD_FILE: $HOME/code/boilerplates/ansible/vault-password
    ANSIBLE_ROLES_PATH: ../../../ansible/roles
