---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian11
    image: geerlingguy/docker-debian11-ansible:latest
    command: ""
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      - /var/run/dbus
    cgroupns_mode: host
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      debian11:
        ansible_user: ansible
  env:
    ANSIBLE_VAULT_PASSWORD_FILE: $HOME/code/boilerplates/ansible/vault-password
