---
scenario:
  test_sequence:
    - create
    - converge
    #- idempotence # TODO: Find a better way to ensure idempotence
    - verify
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bullseye
    image: geerlingguy/docker-debian11-ansible:latest
    command: ""
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      - /var/run/dbus
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: jammy-jellyfish
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      - /var/run/dbus
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: focal-fossa
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ""
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      - /var/run/dbus
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: fedora37
    image: geerlingguy/docker-fedora37-ansible:latest
    command: ""
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      - /var/run/dbus
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: rockylinux9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    command: ""
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      - /var/run/dbus
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      bullseye:
        ansible_user: ansible
      focal-fossa:
        ansible_user: ansible
      jammy-jellyfish:
        ansible_user: ansible
  env:
    #ANSIBLE_VAULT_PASSWORD_FILE: $HOME/code/boilerplates/ansible/vault-password
    ANSIBLE_ROLES_PATH: ../../../ansible/roles
    ANSIBLE_STDOUT_CALLBACK: yml
