---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age14rdalns3kt08ysdz68gcat6gw6wzkuepf0uk9dmzdsz62ugvwumsqeappp
  - path_regex: ansible/.*\.sops\.ya?ml
    encrypted_regex: ": (.+)"
    key_groups:
      - age:
          - age1mt8vvreywnq0972a6y5sxa6klqn8jfezkurkm2trsav42mk56gcqkcu276
  - path_regex: terraform/.*\.sops\.ya?ml
    encrypted_regex: ": (.+)"
    key_groups:
      - age:
          - age1mt8vvreywnq0972a6y5sxa6klqn8jfezkurkm2trsav42mk56gcqkcu276