---
media_path: /mnt/media
container_path: /data
arr_uid: "1000"
arr_gid: "1000"
docker_sock: /var/run/docker.sock:/var/run/docker.sock:ro
docker_network:
    - misc

cname_records:
  - docs
  - vault
  - rss
  - kavita

common_env: &common_env
  TZ: America/New_York
  PUID: "{{ arr_uid }}"
  PGID: "{{ arr_gid }}"

service_definitions:
  - name: winxuu
    image: chkpwd/winxuu:latest
    ports: [3389:3389]

  - name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/syncthing:/config"
      - "{{ configuration_path }}/syncthing/data:/data"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

  - name: bitwardenrs
    image: "vaultwarden/server:latest"
    ports: [8086:80]
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/bitwardenrs:/data"

  - name: swag
    image: "{{ linuxserver_image }}/swag:latest"
    ports:
      - 443:443
      - 80:80
    env:
      <<: *common_env
      URL: chkpwd.com
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      EMAIL: mentality@protonmail.com
      STAGING: "false"
      DOCKER_MODS: linuxserver/mods:swag-auto-reload
    volumes:
      - "{{ configuration_path }}/swag:/config"

  - name: unifi
    image: "lumel/unifi-controller"
    ports:
      - '3478:3478/udp'
      - '10001:10001/udp'
      - '8080:8080'
      - '8085:8081'
      - '8443:8443'
      - '8843:8843'
      - '8880:8880'
      - '6789:6789'
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/unifi:/usr/lib/unifi/data"

  - name: bookstack
    image: "{{ linuxserver_image }}/bookstack"
    env:
      <<: *common_env
      APP_URL: https://docs.chkpwd.com
      DB_HOST: bookstack_db
      DB_USER: bookstack
      DB_DATABASE: bookstackapp
      DB_PORT: '3306'
      DB_PASS: "{{ USR_PASSWORD_SOPS }}"
    ports: [6875:80]
    volumes:
      - "{{ configuration_path }}/bookstack:/config"
    links: bookstack_db

  - name: bookstack_db
    image: "{{ linuxserver_image }}/mariadb"
    env:
      <<: *common_env
      MYSQL_ROOT_PASSWORD: "{{ USR_PASSWORD_SOPS }}"
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: "{{ USR_PASSWORD_SOPS }}"
    volumes:
      - "{{ configuration_path }}/bookstack_db:/config"

  - name: homer
    image: b4bz/homer
    ports: [8081:8080]
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/homer:/www/assets"
  
  - name: homepage
    image: ghcr.io/benphelps/homepage:latest
    ports: [3000:3000]
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/homepage:/app/config"
      - "{{ docker_sock }}"

  - name: code-server
    image: "{{ linuxserver_image }}/code-server"
    ports: [9443:8443]
    env: "{{ common_env }}"
    volumes:
      - "{{ configuration_path }}/code:/config"
      - "{{ configuration_path }}/homer:/config/homer:rw"

  - name: freshrss
    image: "{{ linuxserver_image }}/freshrss:latest"
    env: "{{ common_env }}"
    ports: [8087:80]
    volumes:
      - "{{ configuration_path }}/freshrss:/config"

  - name: kavita
    image: kizaing/kavita:latest
    volumes:
      - "{{ configuration_path }}/kavita:/kavita/config"
      - "{{ configuration_path }}/kavita/data:/books"
    env:
      <<: *common_env
    ports: [8083:5000]

  - name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NOTIFICATION_TITLE_TAG: "Horizon"
      WATCHTOWER_SCHEDULE: "0 7 */10 * *"
      WATCHTOWER_NOTIFICATION_URL: "{{ DISCORD_TOKEN }}"
      WATCHTOWER_MONITOR_ONLY: "false"
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
