apiVersion: v1
kind: Service
metadata:
  name: portainer-svc
  namespace: apps
  labels:
    app: portainer
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: portainer
