---
all:
  hosts:
    localhost:
  children:
    vsphere:
      children:
        esxi_hosts:
        vcenter:

    vcenter:
      hosts:
        ronin:

    esxi_hosts:
      hosts:
        # esx[1:3]:
        octane:
        caustic:

    guests:
      children:
        docker_hosts:
        media_server:
        k3s:
      hosts:
        stable-diffusion:
        cockpit:

    windows:
      hosts:
        loba:
        bloodhound:
      vars:
        ansible_become_method: runas
        ansible_become_user: "{{ ansible_user }}"

    docker_hosts:
      hosts:
        mirage:
        horizon:
        valkyrie:
        crypto:
        node-01:
    
    k3s_cluster:
      children:
        master:
        #workers:

    master:
      hosts:
        kubes-cp-1:
          ansible_host: 172.16.16.201
        kubes-cp-2:
          ansible_host: 172.16.16.202
        kubes-cp-3:
          ansible_host: 172.16.16.203

    printers:
      hosts:
        rampart:
      vars:
        ansible_user: pi
        ansible_become_user: pi

    media_server:
      hosts:
        mirage:
    
    devops:
      hosts:
        crypto:

    dev:
      children:
        staging:

    staging:
      hosts:
        jumpbox-dev: 
          ansible_host: 172.16.16.232

    cloud:
      hosts:
        149.28.65.221:

    onprem:
      children:
        vsphere:

    datacenter:
      children:
        cloud:
        onprem:
