ansible_user: hyoga
ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBK2VnKgOX7i1ISETheqjAO3/xo6D9n7QbWyfDAPsXwa crypto"

packages:
  - zsh
  - vim
  - htop
  - ranger
  - nfs-common

ansible_dest: /home/hyoga/code/boilerplates/ansible
template_path: "{{ ansible_dest }}/roles/code-server/templates"
