shell: /usr/bin/zsh

guid: 1000

ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKEEL7L9/Qeo0tE9vfbMWF54eydaP+waql4T7EFyjn8s"

packages:
  - zsh
  - vim
  - htop
  - ranger

ansible_dest: /home/hyoga/code/boilerplates/ansible
template_path: "{{ ansible_dest }}/roles/code-server/templates"