---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.6.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 30m
  values:
    controller:
      replicaCount: 3

      service:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 172.16.16.204
