apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: 6.3.6
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: monitoring
  interval: 5m
  values:
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: podinfo.local.chkpwd.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
