---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app recyclarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    global:
      nameOverride: *app
    controller:
      type: cronjob
      cronjob:
        schedule: '@daily'
    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: 5.0.3@sha256:7d74dbc921c36fe1c13ec21520f1e300ccac202bb249b3c7be6b42c588b20a84
    command: ['/app/recyclarr/recyclarr']
    args: ['sync']

    service:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: recyclarr-config
        mountPath: /config/recyclarr.yml
        subPath: recyclarr.yml
        defaultMode: 775
        readOnly: true

    resources:
      requests:
        cpu: 10m
        memory: 100M
      limits:
        memory: 110M
