---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.539@sha256:dc7860e1117cb040435c2eace3fc4d67a64672e671c3e692d19df2a98d4dede4

    env:
      TZ: "America/New_York"
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 8989
      SONARR__APPLICATION_URL: "https://sonarrk3s.local.chkpwd.com"
      SONARR__LOG_LEVEL: info

    hostname: sonarr

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "Sonarr"
          hajimari.io/icon: mdi:television-classic
          hajimari.io/info: Show discovery agent
          hajimari.io/group: media
        hosts:
          - host: &host "sonarrk3s.local.chkpwd.com"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        existingClaim: sonarr-media
        mountPath: /data
        readOnly: false

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
        - 100

    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 5000Mi
