- name: Check code-server binary exists
  stat:
    path: "/usr/lib/code-server/lib/vscode/bin/remote-cli/code-server"
    follow: true
  register: code_server_exists

- name: Check installed code-server version
  shell: 'set -o pipefail; code-server --version | grep -P -o "(?<=^|info  )\d+(\.\d+)+(-[^ ]+)?"'
  args:
    executable: /bin/bash
  register: code_server_version
  when: code_server_exists.stat.exists
  changed_when: false

- name: Grabbing latest release from github api
  ansible.builtin.uri:
    url: https://api.github.com/repos/coder/code-server/releases/latest
  register: code_server_latest_release

- name: Set code-server latest version
  ansible.builtin.set_fact:
    code_server_ver: "{{ code_server_latest_release.json.tag_name }}"
