---
- name: Create Git directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/code/boilerplates
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: false

- name: Check if the directory exists
  ansible.builtin.stat:
    path: /home/{{ ansible_user }}/code/boilerplates/ansible
  register: repo_directory

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/chkpwd/boilerplates.git
    dest: /home/{{ ansible_user }}/code/boilerplates
  when: not repo_directory.stat.exists
  become: false

- name: Create a symbolic link to .vscode settings file
  ansible.builtin.file:
    src: /home/hyoga/code/boilerplates/.vscode/settings.json
    dest: /home/hyoga/code/.vscode/settings.json
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link