---
- name: Add the Hashicorp repo for Fedora family
  ansible.builtin.yum_repository:
    name: hashicorpwat u sed
    description: Hashicorp Repository
    baseurl: https://rpm.releases.hashicorp.com/{{ ansible_distribution_release }}/hashicorp.repo
  become: true
  when: ansible_distribution == 'Fedora'

- name: Add VirtualBox repo
  ansible.builtin.yum_repository:
    name: virtualbox
    description: VirtualBox Repository
    baseurl: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
  when: ansible_distribution == 'Fedora'

- name: Add Microsoft GPG Key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: "{{ keyrings_dir }}/microsoft.asc"
    mode: 0644
    force: true
  register: add_apt_key
  until: add_apt_key is succeeded
  retries: 2
  delay: 2
  become: true

- name: Add the Microsoft Repo
  ansible.builtin.apt_repository:
    filename: microsoft
    repo: deb [signed-by={{ add_apt_key.dest }}] https://packages.microsoft.com/repos/microsoft-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}-prod {{ ansible_distribution_release }} main
  become: true
