---
- name: Copy SSH Keys to remote host
  ansible.builtin.copy:
    src: "{{ ansible_dest }}/roles/code-server/templates/"
    dest: "/home/{{ ansible_user }}/.ssh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: preserve
  notify: Restart ssh daemon

- name: Add .local/bin to the Path
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    insertafter: 'LANG'
    line: 'export PATH=$HOME/.local/bin:$PATH'
  changed_when: false

- name: Set the ZSH_CUSTOM shell var if not present
  ansible.builtin.set_fact:
    zsh_custom: "{{ ansible_env.ZSH_CUSTOM | default('/home/' ~ ansible_user ~ '/.oh-my-zsh/custom', true) }}"

- name: Clone a zsh-autosuggestions repo
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ zsh_custom }}/plugins/zsh-autosuggestions"
