apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: namespaces
  path: ./kubernetes/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
