apiVersion: v1
kind: Secret
metadata:
    name: sops-secrets
    namespace: flux-system
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:kHH3yOATHazUifTdYTNCb000pkzKVl7H94F6Wq3EmofQBq60DxbYxg==,iv:exSWkIvvnGyV1amuh5yPUIx8h/WhgnNwv+XZkhB5mvg=,tag:Xs1ahVfOsygY2Jt113DUFQ==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uBlgfLEwatyCpzB+5k0vTUAcx/F/MvAK,iv:/IM8YrjK1jvHXZt1rY9JVCwhx22x/8TTuBnPGMBzZ3k=,tag:78g+GDIDLLqyj258u5w+og==,type:str]
    AWX_POSTGRES_PASSWORD: ENC[AES256_GCM,data:HupGWAj57keYlydKYtLkR+r0Zd1+5VGnp1VUPA==,iv:TIxW41zdl+QeW6vR5Eormm13X/ukVqSoPdNbsbSTJcU=,tag:ro8ozIn/NxVSoa7DIC182w==,type:str]
    AWX_POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:aNOH0oyidKg1AufCc3uRYzcP4XQh,iv:Af4OE5nyzlUVkfFrUIOkNjJsBEKVE446C+JOgFe2IHw=,tag:HJ6U6fq/S99bdcb9wXsOpw==,type:str]
    AWX_ADMIN_EMAIL: ENC[AES256_GCM,data:w2kq0/g8dbjXiopf0+GndWr659A6,iv:ErZlDKnt159TIlpoxir3uxY6S19xESUKhLtxEFUgyzI=,tag:oHJDF/uMo8fpAi6R9t2sQw==,type:str]
    ACTION_RUNNER_GIT_TOKEN: ENC[AES256_GCM,data:wd50p9P/SArg8gJcZKxDVhgsOCU/Zw9I4/YwqcyEafpe6RQqtwxTzw==,iv:kpooXx+DLJfkvGyOw8ZSzl7LOkUjKN9yDYvt2XnkO/g=,tag:GpQnynklQt1n/cGtQQHYIw==,type:str]
    API_KEY_SONARR: ENC[AES256_GCM,data:yTHbNy+KTAgfSnzYa5OW8CGZDZxbGnLBRgNloIzAPak=,iv:JLN0jYDaWQKtE1y6BSWlBe7JdOFhbArF5j2em1vWuIg=,tag:xgrIPlYtpkf+bpDvQutwKg==,type:str]
    API_KEY_RADARR: ENC[AES256_GCM,data:fNaLh5QJuZ2L36/NiIA8NABc/SCSSkN4jJ9pMoW+24Y=,iv:sex0aX6oNe2WhvbGsmQmUSRunNB2jTENItXc9E1rNOs=,tag:lYbzlKc2Vk6XSpqt0INhzw==,type:str]
    API_KEY_BAZARR: ENC[AES256_GCM,data:xil4EBvZCiMbvbWFk5Mp5Ne/VJmK8nr/MkMPSM2LVBQ=,iv:/C8Zid+Qigp3mMfdWpJpdDCcneZVr04uPQZLfgo3bRs=,tag:nsl/57hi5j+bbSNullK4cw==,type:str]
    API_KEY_PROWLARR: ENC[AES256_GCM,data:hNmPY1bTDezhUxgR8W3S9KKkJSeyEzxs4xCxUCtu7gs=,iv:dolhhghGh9cdoY1yLraRQblcdW/yrRW/DULSEilBSVM=,tag:UAbEItGU8FznRa208xthCQ==,type:str]
    API_KEY_OPENWEATHERMAP: ENC[AES256_GCM,data:gH5YcxoGhmp13ohUXQa8VU681lyRk3ZQV8vdw8juiZg=,iv:C6X0k+TtzJRUJKe2tnFtvEFCGQ9tjxn2+GhEUn+VSZM=,tag:PORVgVuOFLG8/t2978RkeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R21KT3JqdklkeVF6cytm
            QzRFMUx1T1c5ZlBDajF2Tzl5Rkd6cmdvSlNFCkhVL2lPTjNqbFV6TklnamNvRU1I
            RGJmeC9RL05idUV5OU40dEpXcndSMEEKLS0tIHVKZXVsRis0RFd2UFlXWTIzZm1x
            WU5xRVZaVG5ONVBIYTU0RU1MZktkQm8KDlwe/HtdV+pHgpZkxigRhgTboP37/rE8
            QBDE5MEFMGvTFAxGwfQNDBy636aQCppuz1g9kZ7RSVV22IETeW4oaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T15:50:06Z"
    mac: ENC[AES256_GCM,data:psVPm6bx9iIojTzhsYURey9vGVLVNikKv4KXR6ZuTMvWmfXEOcp0pMzz3sZtVhlUYBp1Aa86nm5U20qZvmcA3l3HtpByapYavhmFyeNcK0vBQPabVrg6BosV/H0YFkqghfWv0GTpEmFLo8fJiVEocukXCxpa0iDSdwxhjfGxcsk=,iv:foQhqnfeiiQe1b0RVqW04n4yyPfpnpCzdsq7W02qU8k=,tag:YLumiTEqz5ii2PZ13nmwJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
