apiVersion: v1
kind: Secret
metadata:
    name: sops-secrets
    namespace: flux-system
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:eZPCkCl2kkSiFl4ZEJA2lL2gg2pxSfV3DWfDtDy/CH10rDpPBdkZ5g==,iv:IrpKDzKfMJTpJ5JbnjJlB0nwtwLhxos0MuyJ+0bW+xk=,tag:RObq9AkcGitxvswrNQ+Ndw==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JCNd3M7SyygROmgslWP2Mjh1eWdkURTB,iv:kbSt385q5yHCqKrJPO6AJbnFbPoQWvJ4v5CHm+hEcO4=,tag:ktGfS80+nJhyYerRF5RNjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jt6ygrmpzce7xent8kul60ekmyrw4gs5n9mu4d6kptkkx5ze9c5q4jj3dx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb0gyOXpubUJMYmRlbU1R
            eHFRRFUxemxiM0Y1b2tIK3BKdk0vUHV5OVg4CmtFN3RGeUY5dmJHeXFCQ2t0MmVG
            dkFTMEYxelc4SkRkdWFBVmxLa0JuajAKLS0tIGRWVDRYemo2N0VkQ1NLR0luSE9V
            c0NCamdWNy9CUkkyeWtVZXI4L1M3SVEKpRBI/7rp/UCgxbbQwnusGiXbVy0p5Apj
            yAvovu6ELCfv9dl4vBHXX32k22tuvHWxcFnIQ3A2lL9NYzErSSmegg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-24T16:14:16Z"
    mac: ENC[AES256_GCM,data:mweHFPLVl9oRhn/72HzbucshBb0mXPsWjQc5KwJUH68M2AS5YNyYXoR9WVnM8/rk3crzMuTPQnzzttBJF3WMSEbku68ou5m6xjYTXF73VH6lLI19r+vCFnSPqNgxGw5PPKxNt0yJdXD2rZ0MVb0YP384AW4/LmTFLAnBMhQGjBc=,iv:RYGmpiupUUbK2hodK14O4mH3RcaRfUbiirH/VQ4JxoY=,tag:wEpDvbbiK9PR7MmvHCCFZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
