---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian11-ansible:latest
    command: ""
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      - /var/run/dbus
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../../tasks/install_docker.yml
    converge: ../../tasks/install_hasupervised.yml
verifier:
  name: ansible
