apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chkpwd-cert
  namespace: cert-manager
spec:
  secretName: chkpwd-cert
  dnsNames:
  - "chkpwd.com"
  - "*.chkpwd.com"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer