---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 15m
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.23.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: ghcr.io/actions-runner-controller/actions-runner-controller
    authSecret:
      create: true
      github_token: ${GITHUB_TOKEN}
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    metrics:
      serviceMonitor: true
    logFormat: json
    githubWebhookServer:
      enabled: true
      logFormat: json

    actionsMetrics:
      # Do note that you also need actionsMetricsServer.enabled=true
      # to deploy the actions-metrics-server whose k8s service is referenced by the service monitor.
      serviceMonitor: true
    actionsMetricsServer:
      enabled: true
      logFormat: json

    resources:
      requests:
        cpu: 10m
        memory: 250M
      limits:
        memory: 450M
