- name: Install dependencies
  ansible.builtin.apt:
    pkg: "{{ dependencies }}"
    state: present

- name: Enable iscsi modprobe module
  community.general.modprobe:
    name: iscsi_tcp
    state: present
