---
- name: Install dependencies
  ansible.builtin.apt:
    update_cache: true
    name: "{{ dependencies }}"
    state: present

- name: Enable iscsi modprobe module
  community.general.modprobe:
    name: iscsi_tcp
    state: present

- name: Build a cluster with HA control plane
  include_role:
    name: xanmanning.k3s
  vars:
    k3s_state: installed
