---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
  namespace: apps
spec:
  interval: 10s
  path: ./kubernetes/apps/web/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: web
              containerPort: 80
