---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-http
  namespace: apps
spec:
<<<<<<< HEAD
  replicas: 250
=======
  replicas: 500
>>>>>>> 26b95d88b9f728b96279f385e226f4ade8545aa3
  selector:
    matchLabels:
      app: nginx-http
  template:
    metadata:
      labels:
        app: nginx-http
    spec:
      containers:
        - name: nginx-http
          image: nginxdemos/hello
          ports:
            - name: web
              containerPort: 80
