---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-http
  namespace: apps
spec:
  replicas: 500
  selector:
    matchLabels:
      app: nginx-http
  template:
    metadata:
      labels:
        app: nginx-http
    spec:
      containers:
        - name: nginx-http
          image: nginxdemos/hello
          ports:
            - name: web
              containerPort: 80
