- name: Grab latest 'Pet' release from github
  ansible.builtin.uri:
    url: https://api.github.com/repos/knqyf263/pet/releases/latest
    return_content: true
  register: json_reponse

- name: Create Pet Snippet dir
  ansible.builtin.file:
    path: "/home/{{ common_user }}/.config/pet"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: 0644

- name: "Downloading 'Pet' {{ json_reponse.json.tag_name }}"
  loop: "{{ json_reponse.json.assets }}"
  when: "'linux_amd64.tar.gz' in item.name"
  ansible.builtin.get_url:
    url: "{{ item.browser_download_url }}"
    dest: /tmp/pet_amd64.tar.gz
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: 0644
  no_log: true

- name: Unarchive the 'Pet' tar file
  ansible.builtin.unarchive:
    src: /tmp/pet_amd64.tar.gz
    dest: "/tmp"
    remote_src: true

- name: Move the 'Pet' binary to local bin
  ansible.builtin.copy:
    src: "/tmp/pet"
    dest: "/usr/local/bin/"
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: 0755
    remote_src: true
  become: true
