- name: Include | logrotate
  ansible.builtin.include_role:
    name: arillso.logrotate
  vars:
    logrotate_global_config: false
    logrotate_applications:
      - name: custom_logging
        definitions:
          - logs:
              - /var/log/syslog.log
              - /var/log/messages
            options:
              - daily
              - size 20M
              - missingok
              - rotate 10
              - compress
              - delaycompress
              - notifempty
              - create 640 root adm
              - sharedscripts

- name: Health Check logrotate Service
  ansible.builtin.service:
    name: logrotate
    state: started