- name: Include | logrotate
  ansible.builtin.include_role:
    name: arillso.logrotate
  vars:
    logrotate_global_config: false
    logrotate_applications:
      - name: custom_logging
        definitions:
          - logs:
              - /var/log/syslog.log
              - /var/log/messages
            options:
              - daily
              - size 20M
              - missingok
              - rotate 10
              - compress
              - delaycompress
              - notifempty
              - create 640 root adm
              - sharedscripts

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Register logrotate service status
  set_fact:
    logrotate_status: >-
      {{ 
        ansible_facts['services']['logrotate.service']
        if 'logrotate.service' in ansible_facts['services']
        else 'unknown'
      }}

- name: Check if logrotate service is failed
  ansible.builtin.debug:
    msg: "logrotate service has failed"
  when: ansible_facts.services['logrotate.service'].state == 'failed'
