---
- name: Create a login user
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: "{{ usr_password_sops }}"
    # groups:
    #  - sudo
    # append: true # If false, the above groups are the only groups provided to the user
    state: present
  become: true

- name: Chmod the user home directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: false
  become: true

- name: Allow sudo group to have passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: true


