---
- name: "Install the essentials on the target"
  hosts: all
  become: true
  
  roles:
    - system 
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user }}"
          oh_my_zsh:
            theme: bira
            update_mode: auto
            update_frequency: 3
            plugins:
              - git
              - zsh-autosuggestions