---
- name: "Install docker and docker-compose on the target"
  hosts: docker_hosts
  become: true

  vars:
    pip_install_packages:
      - name: docker
    docker_edition: 'ce'
    docker_package_state: latest
    docker_users: hyoga

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
