---
- name: Set the Locale
  hosts: all
  become: yes

  vars:
    timezone: "America/New_York"

  tasks:

    - name: Locale | Set timezone
      community.general.timezone:
        name: "{{ timezone | default('America/New_York') }}"