---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app bazarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.2.1

    env:
      TZ: "America/New_York"
      BAZARR__INSTANCE_NAME: "{{ .Release.Name }}"
      BAZARR__PORT: &port 6767
      BAZARR__APPLICATION_URL: "https://{{ .Release.Name }}k3s.${LOCAL_DOMAIN}"
      BAZARR__API_KEY: ${API_KEY_BAZARR}
      BAZARR__AUTHENTICATION_METHOD: Forms
      BAZARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
      BAZARR__LOG_LEVEL: info

    hostname: *app

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Bazarr"
          gethomepage.dev/group: "Media Automation"
          gethomepage.dev/icon: "{{ .Values.global.nameOverride }}"
          gethomepage.dev/description: "Subtitles Automation Tool."
          gethomepage.dev/widget.type: "{{ .Values.global.nameOverride }}"
          gethomepage.dev/widget.url: "http://{{ .Values.global.nameOverride }}.media.svc.cluster.local"
          gethomepage.dev/widget.key: "${API_KEY_BAZARR}"
        hosts:
          - host: &host "{{ .Values.global.nameOverride }}k3s.${LOCAL_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/
        mountPath: /data

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [568]

    resources:
      requests:
        cpu: 10m
        memory: 500M
      limits:
        memory: 600M
