---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app bazarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.2.1@sha256:ec73f87c96b7480273775d0f0541a58f2c1ead58c675be3effac0a4e9021256f

    env:
      TZ: "America/New_York"

    hostname: bazarr

    service:
      main:
        ports:
          http:
            port: &port 6767

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "bazarrk3s.local.chkpwd.com"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
      media:
        enabled: true
        type: nfs
        server: "cockpit.${LOCAL_DOMAIN}"
        path: /mnt/data/
        mountPath: /data

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [568]

    resources:
      requests:
        cpu: 10m
        memory: 500M
      limits:
        memory: 600M
