---
- name: Check disk space
  hosts: linux

  tasks:
    - name: Get free disk space
      shell: |
        set -o pipefail
        df -h /tmp --output\=avail | tail -n 1 
      register: disk_usage
