---
- name: Check Pending Reboots
  hosts: all
  become: yes

  tasks:
    - name: Check if system reboot is required
      become: true
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
