apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/AnaisUrlichs/react-article-display
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/manifests/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kubernetes/infrastructure/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: react-app
  targetNamespace: app