---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: awx-operator
      version: 2.2.1
      sourceRef:
        kind: HelmRepository
        name: awx-chart
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    AWX:
      enabled: true
      name: awx
      spec:
        replicas: 2
        admin_user: admin
        admin_email: ${AWX_ADMIN_EMAIL}
        admin_password_secret: awx-admin-password
        ingress_type: ingress
        ingress_class_name: nginx
        hostname: awx.${LOCAL_DOMAIN}
        projects_persistence: true
        projects_existing_claim: awx-operator-claim
        projects_storage_size: 1Gi
        projects_storage_class: longhorn
