- name: Copy mainsail configs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/printer_data/config/test/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_fileglob:
    - "templates/config/*.j2"