k3s_release_version: "v1.26.1+k3s1"
k3s_install_hard_links: true
k3s_become: true
k3s_debug: false
k3s_etcd_datastore: true

kube_vip_address: 172.16.16.200

k3s_server_manifests_urls:
  # Kube-vip RBAC
  - url: https://raw.githubusercontent.com/kube-vip/kube-vip/main/docs/manifests/rbac.yaml
    filename: custom-kube-vip-rbac.yaml
k3s_server_manifests_templates:
  - kube-vip-static-pod.yaml.j2

k3s_registration_address: "{{ kubevip_address }}"

systemd_dir: /etc/systemd/system

ansible_user: 'hyoga'
