---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-cm
  namespace: tools
type: Opaque
stringData:
  DB_PORT: "5432"
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.tools.svc.cluster.local:3003
  IMMICH_SERVER_URL: http://immich-server.tools.svc.cluster.local:3001
  IMMICH_WEB_URL: http://immich-web.tools.svc.cluster.local:3000
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  REDIS_DBINDEX: "10"
  REDIS_HOSTNAME: immich-redis.tools.svc.cluster.local
  REDIS_PORT: "6379"
  TYPESENSE_DATA_DIR: /config
  TYPESENSE_HOST: immich-typesense.tools.svc.cluster.local
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  NODE_ENV: production
  LOG_LEVEL: verbose
