---
k3s_control_node: true

k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    - "{{ kube_vip_address }}" # Floating LoadBalancer IP for Control Plane API
    - k3s-vip.local.chkpwd.com
  docker: false
  flannel-backend: "vxlan" # quote
  disable:
    - metrics-server
    - servicelb
    - traefik
    - local-storage
  write-kubeconfig-mode: "0644"
