---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.5.5
      sourceRef:
        kind: HelmRepository
        name: bitnami-chart
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      postgresql:
        auth:
          postgresPassword: "${POSTGRES_ADMIN_PASSWORD}"
          username: awx
          password: "${POSTGRES_PASSWORD}"
          database: awx
    primary:
      persistence:
        enabled: true
        existingClaim: awx-postgresql
    volumePermissions:
      enabled: true
