---
apiVersion: v1
kind: Secret
metadata:
  name: awx-operator-secret
  namespace: development
stringData:
  password: ${AWX_ADMIN_PASSWORD}
  postgres-password: ${AWX_POSTGRES_PASSWORD}
  replication-password: ${AWX_REPLICATION_PASSWORD}
type: Opaque
