# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: awx-operator-claim
#   namespace: development
# spec:
#   storageClassName: longhorn
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
#     limits:
#       storage: 10Gi
