---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-operator-claim
  namespace: development
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-postgresql-claim
  namespace: development
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
