---
- name: Disable News Feed
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: TaskbarDa
    data: 0
    type: dword

- name: Set 'Enhance Pointer Precision' to off
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Mouse
    name: MouseSpeed
    data: 0
    type: dword

- name: Disable Desktop Icons
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: NoDesktop
    data: 1
    type: dword

- name: Enable File Extensions
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword

- name: Enable Hidden Files
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: Hidden
    data: 1
    type: dword

- name: Remove Teams Chat
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: TaskbarMn
    data: 0
    type: dword

- name: Allow RDP Connections
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    data: 0
    type: dword
