---
- name: Restart ssh daemon
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true

- name: Restart code-server
  ansible.builtin.service:
    name: code-server@{{ ansible_user_id }}.service
    state: restarted
  become: true
