---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-metallb
  namespace: flux-system
spec:
  path: ./kubernetes/core/metallb-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 30s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-metallb
  path: ./kubernetes/core/metallb-system/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 30s
