---
- name: Stop Docker Service
  ansible.builtin.service:
    name: docker
    state: stopped
  listen: Restart Docker Service

- name: Delete Docker Data
  ansible.builtin.file:
    path: /var/lib/docker
    state: absent
  listen: Restart Docker Service

- name: Start Docker Service
  ansible.builtin.service:
    name: docker
    state: started
  listen: Restart Docker Service

- name: Restart SSH daemon
  ansible.builtin.service:
    name: sshd
    state: restarted
