---
name: CI
'on':
  push:
    branches:
      - master
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian11
          
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: Install test dependencies.
        run: |
          export PIP_NO_WARN_ABOUT_ROOT_USER=0
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ansible/requirements.txt

      - name: Run Molecule tests.
        run: "cd ansible/roles/code-server && molecule test"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
