---
name: CI
'on':
  push:
    branches:
      - master
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian10
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker yamllint ansible-lint

      - name: Run Molecule tests.
        run: "cd ansible/roles/haos && molecule test"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
